### ISSUE TITLE
TypeError: Cannot read property '1' of undefined with deadfile dependency

### ISSUE THREAD

**Issue by nkhiljee** [M-Izadmehr/deadfile#40]
same error keeps repeating ... I cant get any results

deadfile ./src/App.js

   ╭──────────────────────────────────────────────────────────────╮
   │                                                              │
   │                          Dead File!                          │
   │                                                              │
   │   Simply find the unused files in your javascript project.   │
   │                    Press --help for help.                    │
   │                                                              │
   ╰──────────────────────────────────────────────────────────────╯

✔ 614 total assets found in base directory.
⠋ Counting imported assetserr:  TypeError: Cannot read property '1' of undefined
    at checkBabelModuleResolver (/usr/local/lib/node_modules/deadfile/src/handlers/fileResolver.js:26:38)
    at resolve (/usr/local/lib/node_modules/deadfile/src/handlers/fileResolver.js:53:15)
    at UsedAssets.updateSources (/usr/local/lib/node_modules/deadfile/src/handlers/UsedAssets.js:99:38)
    at UsedAssets.checkImports (/usr/local/lib/node_modules/deadfile/src/handlers/UsedAssets.js:142:21)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:79:24)
    at Object.skipThrough (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:186:39)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:78:24)
    at Object.base.Program.base.BlockStatement (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:198:7)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:78:24)
    at Object.full (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:80:7)
err:  TypeError: Cannot read property '1' of undefined
    at checkBabelModuleResolver (/usr/local/lib/node_modules/deadfile/src/handlers/fileResolver.js:26:38)
    at resolve (/usr/local/lib/node_modules/deadfile/src/handlers/fileResolver.js:53:15)
    at UsedAssets.updateSources (/usr/local/lib/node_modules/deadfile/src/handlers/UsedAssets.js:99:38)
    at UsedAssets.checkImports (/usr/local/lib/node_modules/deadfile/src/handlers/UsedAssets.js:142:21)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:79:24)
    at Object.skipThrough (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:186:39)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:78:24)
    at Object.base.Program.base.BlockStatement (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:198:7)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:78:24)
    at Object.full (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:80:7)
err:  TypeError: Cannot read property '1' of undefined
    at checkBabelModuleResolver (/usr/local/lib/node_modules/deadfile/src/handlers/fileResolver.js:26:38)
    at resolve (/usr/local/lib/node_modules/deadfile/src/handlers/fileResolver.js:53:15)
    at UsedAssets.updateSources (/usr/local/lib/node_modules/deadfile/src/handlers/UsedAssets.js:99:38)
    at UsedAssets.checkImports (/usr/local/lib/node_modules/deadfile/src/handlers/UsedAssets.js:142:21)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:79:24)
    at Object.skipThrough (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:186:39)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:78:24)
    at Object.base.Program.base.BlockStatement (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:198:7)
    at c (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:78:24)
    at Object.full (/usr/local/lib/node_modules/deadfile/node_modules/acorn-walk/dist/walk.js:80:7)

**Comment by nathanredblur** [comment]
I have the same issue.
